In [362]:
# 1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.


In [363]:
import numpy as np

In [364]:
def function1():
    arr = np.array([1,7,13,105])
    print(arr)
    print(f"Size = {arr.size}")


In [365]:
function1()

[  1   7  13 105]
Size = 4


In [366]:
# 2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.


In [367]:
def function2():
    n1 = ([10,20,30,90])
    n2 = ([50,20,60,80])
    print(np.greater(n1,n2))
    print(np.greater_equal(n1,n2))
    print(np.less(n1,n2))
    print(np.less_equal(n1,n2))

In [368]:
function2()


[False False False  True]
[False  True False  True]
[ True False  True False]
[ True  True  True False]


In [369]:
#3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.


In [370]:
arr1 = np.zeros(10)
arr2 = np.ones(10)
arr3 = (arr2*5)
arr4 = (arr2*10)
arr5 = (arr2*20)
arr6 = (arr2*50)
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [371]:
#4. Write a NumPy program to create an array of integers from 30 to 70.

In [372]:
arr1 = np.arange(30,70)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [373]:
#5. Write a NumPy program to create an array of integers from 50 to 95.


In [374]:
arr2 = np.arange(50,95)
print(arr2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [375]:
# 6. Write a NumPy program to create an array of all even integers from 20 to 80.


In [376]:
arr3 = np.arange(20,80,2)
print(arr3)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [377]:
# 7. Write a NumPy program to create an array of all odd integers from 20 to 80.


In [378]:
arr4 = np.arange(21,81,2)
print(arr4)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [379]:
# 8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.


In [380]:
arr1 = np.random.randint(10,40,15) 
print(arr1)

[18 33 19 21 39 27 21 34 38 26 33 38 25 39 11]


In [381]:
# 9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.


In [382]:
arr2 = np.random.randint(30,50,10) 
print(arr2)

[38 33 34 49 31 39 30 31 42 40]


In [383]:
# 10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.


In [384]:
arr3 = np.random.randint(50,90,20) 
print(arr3)

[67 51 50 88 72 50 75 52 80 60 65 83 61 66 73 53 53 88 88 63]


In [385]:
# 11. Create any two arrays & perform various mathematical operations.
   # i.e. Addition, Substraction, Multiplication, Divide.


In [386]:
n1 = np.array([11,22,33,44])
n2 = np.array([10,20,30,40])
print(f"N1 = {n1}")
print(f"N2 = {n2}")
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)


N1 = [11 22 33 44]
N2 = [10 20 30 40]
[21 42 63 84]
[1 2 3 4]
[ 110  440  990 1760]
[1.1 1.1 1.1 1.1]


In [387]:
# 12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.


In [388]:
n1 = np.arange(10,22).reshape(3,4)
print(n1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [389]:
# 13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.


In [390]:
n2 = np.eye(3)
print(n2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [391]:
n2 = np.array([1,0,0,0,1,0,0,0,1])
n2 = n2.reshape([3,3])
print(n2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [392]:
# 14. Write a NumPy program to find the number of rows and columns in a given     matrix. 


In [393]:
matrix = np.array([[10, 20, 30], [11, 22, 33]])
 
dimensions = matrix.shape
rows, columns = dimensions
 
print("Rows:", rows)
print("Columns:", columns)

Rows: 2
Columns: 3


In [394]:
# 15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.


In [395]:
n1 = np.array([1,0,0,0,0,0,2,0,0,0,0,0,3,0,0,0,0,0,4,0,0,0,0,0,5])
n1 = n1.reshape([5,5])
print(n1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [396]:
# 16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [397]:
n1 = np.random.random((3, 3, 3))
print(n1)

[[[0.38861444 0.62394366 0.29369106]
  [0.42440632 0.74509981 0.04659326]
  [0.43940354 0.73319104 0.0620211 ]]

 [[0.71848494 0.31252013 0.11661199]
  [0.51549246 0.85844101 0.67291007]
  [0.34230032 0.94630029 0.20954323]]

 [[0.9789328  0.50562115 0.21734506]
  [0.50374303 0.50095598 0.99723409]
  [0.99540468 0.83977781 0.21702231]]]


In [398]:
# 17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.


In [399]:
n1 = np.random.random((2, 3, 4))
print(n1)

[[[0.83044254 0.18292245 0.332864   0.26852097]
  [0.73392089 0.73316393 0.34635352 0.63385573]
  [0.50454359 0.51594659 0.73065354 0.08040804]]

 [[0.61866756 0.89946334 0.1865815  0.70369512]
  [0.59665007 0.48302971 0.50281813 0.08805161]
  [0.3648998  0.30545987 0.67109404 0.74440394]]]


In [400]:
# 18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.


In [401]:
n1 = ([11,22,33,44])
n1 = np.array(n1)
print(n1)

[11 22 33 44]


In [402]:
# 19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [403]:
n2 = np.arange(2, 11).reshape(3, 3)
print(n2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [404]:
# 20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [405]:
n3 = np.arange(12,38)
print(n3)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [406]:
# 21. Write a NumPy program to reverse an array (the first element becomes the last).


In [407]:
n3 = np.arange(12,38)
n3 = n3[::-1]
print(n3)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [408]:
# 22. Write a NumPy program to convert an data type into to a floating type.


In [409]:
n1 = ([11,22,33,44])
n1 = np.asfarray(n1)
print(n1)

[11. 22. 33. 44.]


In [410]:
# 23. Write a NumPy program to convert a list array.


In [411]:
n1 = ([11,22,33,44])
n1 = np.array(n1)
print(n1)

[11 22 33 44]


In [412]:
# 24.Write a NumPy program to get the element-wise remainder of an array of division.


In [413]:
n1 = np.arange(7)
print(np.remainder(n1, 5)) 


[0 1 2 3 4 0 1]


In [ ]:
# 25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.